### ISSUE TITLE
Inflate is broken

### ISSUE THREAD

**Issue by JimBobSquarePants** [SixLabors/ZlibStream#17]
I don't know when it happened as the coverage wasn't good enough to catch it but the round-trip tests now fail due to error introduced during optimization.

**Comment by brianpopow** [comment]
I am not sure, if I understand. There is a round trip test which does encode/decode. This test does **not** seem to fail. Is this test failing for you? Or is a different encode/decode scenario failing?

**Comment by JimBobSquarePants** [comment]
OK. I'm really confused. 

I was convinced this was broken and have no memory at all of fixing it!
