### ISSUE TITLE
Span/Memory API

### ISSUE THREAD

**Issue by HurricanKai** [SixLabors/ZlibStream#5]
APIs that take Span/Memory would be immensely useful.
They'd likely look like the System UTF8 methods, which both take a source and target, reporting how many bytes were written and if there is any left. This could work especially well with a separate method finding the minimum / maximum amount of bytes that could be produced based on the amount of source bytes. (I have no real knowledge about ZLib so excuse if this simply is impossible or the estimates would be so off, it'd be useless.)

**Comment by JimBobSquarePants** [comment]
Agreed. Implementing a Decoder/Encoder pair would be very useful.

This will require refactoring `ZlibStream`'s `NextIn` and `NextOut` properties to use pointers and also updating the `Adler32` implementation to use pointers also.

**Comment by HurricanKai** [comment]
I'd argue it'd be much better to rework them to use Span/Memory instead. Seems like that'd be much easier

**Comment by JimBobSquarePants** [comment]
You can only store ref structs as properties of ref structs so require a pointer instead. Should be not too bad a change

**Comment by JimBobSquarePants** [comment]
Ok... So I've added read/write span to the stream APIs. However, they are only present in target frameworks that support the new overrides. e.g. .NET Core 3.0+

 I can now use the basis of this work to implement something like [BrotliDecoder](https://source.dot.net/#System.IO.Compression.Brotli/System/IO/Compression/dec/BrotliDecoder.cs,a79286f457cf4dd8).
