### ISSUE TITLE
How to use? Exception while decompressing

### ISSUE THREAD

**Issue by hjred** [SixLabors/ZlibStream#7]
Hello there,

I am trying to use this library, as SIMD enabled managed zlib implementation is the way I want to go for a hobby project.

So I am trying a roundtrip with an input text file containing 200 'a' characters.

With this code:

        private static void Main(string[] args)
        {
            {
                using FileStream inStream = File.OpenRead(@"D:\test\CrashTest\in.txt");
                using FileStream deflateOutStream = File.OpenWrite(@"D:\test\CrashTest\out.comp");

                ZlibOutputStream zlib = new ZlibOutputStream(deflateOutStream, CompressionLevel.Level6);
                inStream.CopyTo(zlib);
            }

            {
                using FileStream inStream = File.OpenRead(@"D:\test\CrashTest\out.comp");
                using FileStream inflateOutStream = File.OpenWrite(@"D:\test\CrashTest\out2.txt");

                ZlibInputStream zlib = new ZlibInputStream(inStream);
                zlib.CopyTo(inflateOutStream);
            }
        }

the Inflate is always running into Exception thrown here: https://github.com/SixLabors/ZlibStream/blob/196c4730ba637a445e840ed7cfe67297e77b47af/src/ZlibStream/ZlibInputStream.cs#L174

with various errors/ZStream states: ZBUFERROR with message "inflating: " for the above file
for another longer file I get ZDATAERROR with message "inflating: incomplete literal/length tree"

Am I using the library correctly?

By the way, I am using Net 5.0 on Windows 10.

**Comment by JimBobSquarePants** [comment]
You're not disposing of the `ZlibOutputStream` instance which is leading to an incomplete write.

**Comment by hjred** [comment]
Hmm, apparently I forgot the using statement for the ZlibStreams :/

**Comment by JimBobSquarePants** [comment]
Easy enough to do. 😄 

Btw if you’re using . NET 5 MS now have a dedicated type for Zlib. I’d probably use that at this point as it’s likely suitable for your needs unless you require very custom configuration.

**Comment by AraHaan** [comment]
Also @JimBobSquarePants I unified my ZlibStreams on my copy of zlib and it seems to work out better for me. Perhaps you could look at how I merged them and do the same thing with this one?

**Comment by JimBobSquarePants** [comment]
@AraHaan Thanks yeah, I'll have a look at merging to the two streams as even I find it a little confusing at the moment. 

>Also I might want to check a few places in the code as well, Rider keeps telling me there are a few if statements that is always false (and code inside them). I would double check if they actually ever are used and if not nuke that dead code.

That's likely as there's some config code used when using GZIP but I might actually introduce that so I'm leaving it.

>the people there are cool and not toxic.

Funny you should say that but I ended up getting kicked off that Discord for after arguing privately with a MOD (_They told me off for reacting to a post calling one of libraries shit, I said they weren't doing their job properly because they hadn't moderated the post which had sat there for two weeks before I found it via searching for my library name in order to answer questions_)

**Comment by AraHaan** [comment]
> @AraHaan Thanks yeah, I'll have a look at merging to the two streams as even I find it a little confusing at the moment.
> 
> > Also I might want to check a few places in the code as well, Rider keeps telling me there are a few if statements that is always false (and code inside them). I would double check if they actually ever are used and if not nuke that dead code.
> 
> That's likely as there's some config code used when using GZIP but I might actually introduce that so I'm leaving it.
> 
> > the people there are cool and not toxic.
> 
> Funny you should say that but I ended up getting kicked off that Discord for after arguing privately with a MOD (_They told me off for reacting to a post calling one of libraries shit, I said they weren't doing their job properly because they hadn't moderated the post which had sat there for two weeks before I found it via searching for my library name in order to answer questions_)

yes that was the official C# discord one, the one I sent a link to was made by @Almantask (aka Kaisinel#4921 on discord).

**Comment by JimBobSquarePants** [comment]
Thanks, I'll check it out.

**Comment by AraHaan** [comment]
> Thanks, I'll check it out.

Also they had to do verifications because they had bots spam users pm's with scams.

**Comment by AraHaan** [comment]
<img width="743" alt="image" src="https://user-images.githubusercontent.com/15173749/116017907-d2b8a000-a60e-11eb-8a8d-820eafc75c6a.png">
<img width="863" alt="image" src="https://user-images.githubusercontent.com/15173749/116018061-32af4680-a60f-11eb-8fc5-c225ff32a9b6.png">
<img width="883" alt="image" src="https://user-images.githubusercontent.com/15173749/116018098-49559d80-a60f-11eb-9a55-bddfbb5ae8ce.png">

On my zlib this is what I see rider saying on my latest default branch commit.
https://github.com/Elskom/zlib.managed/

Also I been changing the codebase to use features from c# 9 like pattern matching and replacing a lot of callsites using ``==`` and ``!=`` with ``is`` and ``is not``.

**Comment by JimBobSquarePants** [comment]
@AraHaan  I don't those warnings in my codebase using Rider (with or without the `is` operator). They're also not in the areas of config code I was referring to either. You might be getting a false positive but our codebases have diverged a lot so it's hard to tell. 

Let's not sidetrack this issue anyway, Ill close it now. I've just enabled [Discussions](https://github.com/SixLabors/ZlibStream/discussions) for chitchat.
