### ISSUE TITLE
ZlibInputStream constructor naming

### ISSUE THREAD

**Issue by HurricanKai** [SixLabors/ZlibStream#9]
I'm not sure whether the ZlibInputStream has two constructors with the name "output" and one with the name "input" as the first parameter intentionally or whether this is a mistake, but it's very unclear when to use ZlibInputStream and when to use ZlibOutputStream, and when to use what constructor.
Some clarification in the documentation would be very helpful 😄

**Comment by JimBobSquarePants** [comment]
That's just a copy/paste. 

Not really worth opening an issue for, perhaps it would have been better raised as a [discussion](https://github.com/SixLabors/ZlibStream/discussions/categories/q-a)
